server:
  port: 8081

spring:
  application:
    name: zhao-nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.92.130:8848
    sentinel:
      transport:
        port: 8710
        dashboard: 192.168.92.130:8588

management:
  endpoints:
    web:
      exposure:
        include: "*"